import arcticon from '../../images/arct-icon.png'
import authorimage from '../../images/author-image.jpg'
import banner1large1 from '../../images/banner-large-1.jpg'
import bannerSmallImage from '../../images/banner-small-image.png'  
// import arcticon from '../../images/arct-icon.png'
// import arcticon from '../../images/arct-icon.png'
// import arcticon from '../../images/arct-icon.png'
// import arcticon from '../../images/arct-icon.png'
// import arcticon from '../../images/arct-icon.png'
// import arcticon from '../../images/arct-icon.png'
// import arcticon from '../../images/arct-icon.png'
// import arcticon from '../../images/arct-icon.png'
// import arcticon from '../../images/arct-icon.png'
// import arcticon from '../../images/arct-icon.png'
// import arcticon from '../../images/arct-icon.png'
// import arcticon from '../../images/arct-icon.png'
// import arcticon from '../../images/arct-icon.png'
// import arcticon from '../../images/arct-icon.png'
// import arcticon from '../../images/arct-icon.png'
// import arcticon from '../../images/arct-icon.png'
// import arcticon from '../../images/arct-icon.png'
// import arcticon from '../../images/arct-icon.png'
// import arcticon from '../../images/arct-icon.png'
// import arcticon from '../../images/arct-icon.png'
 